version: 2
updates:
  - package-ecosystem: npm
    directory: "/"                # root of your project
    schedule:
      interval: weekly            # or "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
