name: CI & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Validate Build Output
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: Build did not produce the dist directory."
            exit 1
          fi

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch origin gh-pages || echo "No gh-pages branch yet"
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard
          # Verify if 'dist' exists and copy the files
          if [ -d "dist" ]; then
            cp -r dist/* . || echo "No visible files to copy"
            cp -r dist/.* . 2>/dev/null || echo "No hidden files to copy"
            git add -A
            git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
            git push origin gh-pages || { echo "Error: Failed to push to gh-pages"; exit 1; }
          else
            echo "Error: dist directory does not exist. Build may have failed."
            exit 1
          fi
