name: CI & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Validate Build Output
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: Build did not produce the dist directory."
            exit 1
          fi

      - name: List dist contents
        run: ls -la dist || echo "dist directory not found"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Check if the gh-pages branch exists
          if git rev-parse --verify gh-pages >/dev/null 2>&1; then
            git checkout gh-pages
            git pull origin gh-pages --rebase || true
          else
            git checkout --orphan gh-pages
          fi

          git reset --hard

          # Verify if 'dist' exists and copy the files
          if [ -d "dist" ]; then
            # Copy visible files
            if ! cp -r dist/* .; then
              echo "Error: Failed to copy visible files from 'dist' directory."
              exit 1
            fi

            # Copy hidden files (e.g., .htaccess) from the 'dist' directory to ensure all necessary files are deployed
            if ! find dist -mindepth 1 -maxdepth 1 -name ".*" ! -name "." ! -name ".." -exec cp -r {} . \;; then
              echo "Error: Failed to copy hidden files from 'dist' directory."
              exit 1
            fi

            git add -A

            # Check if there are changes before committing
            if ! git diff --cached --quiet; then
              git commit -m "Deploy to GitHub Pages"
              git push origin gh-pages --force || { echo "Error: Failed to push to gh-pages"; exit 1; }
            else
              echo "No changes to commit"
            fi
          else
            echo "Error: 'dist' directory not found. Deployment aborted."
            exit 1
          fi
